#+Title: Feline Display Manager

* Introduction
  This is a fork of TDM. It aims to improve TDM and the support of no-X environment. It is also able to be shown even when an X session is running, it is able to start multiple X sessions, and it is more Wayland ready.
  NB : This project is NOT related to FVWM.
  
* Prerequisites
  - bash : FDM is a bash-based software
  - make : for the installation
  - startx : FDM uses startx in order to start the sessions
    
* Install
  In first, choose a good prefix, and eventually edit the Makefile according to your prefix choice. If you don't know which one to use, "/usr/local" is a good choice. Next build and install FDM with the following commands :
  : make
  : sudo make install
  : make clean
  And finally, please add the installed binaries, stored in ~$PREFIX/bin/~, to your path.

* Uninstall
  The easiest way to uninstall FDM is to have to Makefile used with the install. If it's the case, you will be able to uninstall FDM with the following command :
  : sudo make uninstall

  Else there are two possibilities :
  1. FDM is installed in its own folder :
     In this case, you will have only to delete the FDM folder.
  2. FDM is installed in a folder used by other stuff of your OS :
     You will have to manually delete the following files and directory : 
     : $PREFIX/bin/fdm
     : $PREFIX/bin/fdmctl
     : $PREFIX/bin/fdm_core
     : $PREFIX/etc/fdm.cfg
     : $PREFIX/share/fdm/
  
* Configuration
  To autostart FDM each time an user connects itself to a consol next to a logging, you have to add, at the end of your ~\~/.bash_profile~ if your shell is bash, at the end of your ~\~/.zlogin if you use zsh, or at the end of your ~/etc/profile~ if you want to have it enabled for all the users of your system.
  It is possible to execute the startx with additionnal options. To send this options to the startx, you only have to give them to the call to fdm.
  Ex : if you want to execute "startx <choosen session> -- -dpi 96" you will call "fdm -- -dpi 96"

** Global configuration
  The global configuration is done in the $PREFIX/etc/fdm.cfg file.
  - PREFIX : the prefix used to perform the FDM install. Unless you move the folder "fdm" to an other location, you should not change this variable
  - VERSION : the current version
  - UI : the default FDM UI. 
    + "text" : FDM will be launched in the text mode
    + "ncurses" : FDM will be launched in the ncurses mode
  - CONFDIR : the user configuration directory path
  - CACHEDIR : the user cache directory path
  - X : the folder which will store the X sessions
  - WAYLAND : the folder which will store the Wayland sessions
  - EXTRA : the folder which will store the extra sessions
  - DEFAULT : the default session
  - SAVELAST : if "1", the default session will be the latest used session which is not registered as an extra session
  - AUTOSTART : start the default session without showing FDM

** User configuration
   The user configuration is stored in the ~\~/.config/fdm~ directory : 
   - fdminit : command to execute before starting FDM
   - fdmexit : command to execute when quitting fdm, before to start the session
   - directories ~X~, ~Wayland~ and ~extra~ : symbolic links to the session choosen by the user with fdmctl
   - default : symbolic link to the default session. The default session can be changed by the fdmctl command. If the global option "SAVELIST" in the ~$PREFIX/etc/fdm.cfg~ file is enabled, the default session is overriden by the latest session used which is not stored in the ~\~/.config/fdm/extra~ folder
   - cache : folder which contains the session disabled by the fdmctl command.
  
* fdmctl
  fdmctl init: initialize the user configuration directory
  fdmctl list: list all the available sessions
  fdmctl cache: list the sessions of the directory \"cache\"
  fdmctl check <session nale>: check which binary is used by a given session
  fdmctl default [<session name>]: check or define the default session
  fdmctl add <session name> <binary path> [x(default) | w[ayland] | e[xtra]]: add a new session
  fdmctl enable/disable <session name>: enable or disable a session
